//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lycoris.Base.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lycoris.Base.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] ip2region {
            get {
                object obj = ResourceManager.GetObject("ip2region", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 戊边
        ///戍边
        ///戌边
        ///边防
        ///李鹏
        ///刁进平
        ///习尽评
        ///刁进评
        ///刁进平吓抬
        ///习尽评吓台
        ///刁进评下台
        ///下台
        ///吓台
        ///吓抬
        ///毛泽东
        ///周恩来
        ///刘少奇
        ///朱德
        ///彭德怀
        ///林彪
        ///刘伯承
        ///陈毅
        ///贺龙
        ///聂荣臻
        ///徐向前
        ///罗荣桓
        ///叶剑英
        ///李大钊
        ///陈独秀
        ///孙中山
        ///孙文
        ///孙逸仙
        ///邓小平
        ///陈云
        ///江泽民
        ///朱镕基
        ///李瑞环
        ///尉健行
        ///李岚清
        ///胡锦涛
        ///罗干
        ///温家宝
        ///吴邦国
        ///曾庆红
        ///贾庆林
        ///黄菊
        ///吴官正
        ///李长春
        ///吴仪
        ///回良玉
        ///曾培炎
        ///曹刚川
        ///唐家璇
        ///华建敏
        ///陈至立
        ///张德江
        ///俞正声
        ///王乐泉
        ///刘云山
        ///王刚
        ///王兆国
        ///刘淇
        ///贺国强
        ///郭伯雄
        ///胡耀邦
        ///习近平
        ///李克强
        ///张高丽
        ///刘延东
        ///彭丽媛
        ///王岐山
        ///华国锋
        ///曾荫权
        ///习大大
        ///吴帮国
        ///无帮国
        ///无邦国
        ///无帮过
        ///瘟家宝
        ///假庆林
        ///甲庆林
        ///假青林
        ///离长春
        ///习远平
        ///袭近平
        ///李磕墙
        ///贺过墙
        ///和锅枪
        ///胡主席
        ///习主席
        ///毛主席
        ///布什
        ///布莱尔
        ///小泉
        ///纯一郎
        ///萨马兰奇
        ///安南
        ///阿拉法特
        ///普京
        ///默克尔
        ///克林顿
        ///里根
        ///尼克松
        ///林肯
        ///杜鲁门
        ///赫鲁晓夫
        ///列宁
        ///斯大林
        ///马克思
        ///恩格斯
        ///金正日
        ///金日成
        ///萨达姆
        ///胡志明
        ///西哈努克
        ///希拉克
        ///撒切尔
        ///阿罗约
        ///曼德拉
        ///卡斯特罗
        ///富兰克林
        ///华盛顿
        ///艾森豪威尔
        ///拿破仑
        ///亚历山大
        ///路易
        ///拉姆斯菲尔德
        ///劳拉
        ///鲍威尔
        ///奥巴马
        ///梅德 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string sensitive_words_lines {
            get {
                return ResourceManager.GetString("sensitive_words_lines", resourceCulture);
            }
        }
    }
}
